services:
  #db-service
  db:
    image: postgres:15.1-alpine
    container_name: cmisdb_container
    environment:
      - DB_URL=${DATABASE_URL}
    env_file:
      - .env
    ports:
      - "5433:5432"
    hostname: db
    volumes:
      - cmispg_data:/var/lib/postgresql/data
    networks:
      - cmis-net

  #migration_service
  # migration:
  #   image: migrate/migrate
  #   container_name: migration_container
  #   volumes:
  #     - "./db/migrations:/migrations"
  #   environment:
  #     - DATABASE_URL
  #   env_file:
  #     - .env
  #   command: ["-path=db/migrations", "-database=${DATABASE_URL}", "up"]
  #   depends_on:
  #     - db
  #   #restart: on-failure
  #   networks:
  #     - cmis-net
  #backend-web-service
  app:
    container_name: cmis_container
    tty: true
    build: .
    environment:
      - DATABASE_URL
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    networks:
      - cmis-net

volumes:
  cmispg_data:

networks:
  cmis-net:
    driver: bridge